default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails


development:
  <<: *default
  pool: 5
  timeout: 5000
  database: budget_development
  password: rails_user

test:
  <<: *default
  database: budget_test
  password: rails_user
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: budget_production
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
